# Generated by Django 4.1.7 on 2023-03-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Reason', models.CharField(max_length=255)),
                ('Status', models.IntegerField(default=0)),
            ],
        ),
    ]
